### PR TITLE
Add the start of Sass best practices

### PR DESCRIPTION
**Pull request by davegonzalez**
Small addition of Sass/Css to our best practices guide.

### CODE REVIEW

**Comment by sbone** [comment]
Looks good, Dave! Without getting too granular, I think adding a mention of AirBnB's [CSS formatting](https://github.com/airbnb/css#formatting) is worthwhile, like in the JS section. What do you think?

**Comment by ksheurs** [comment]
👍

**Review by sbone — APPROVED** [review]
Looks good, Dave! Without getting too granular, I think adding a mention of AirBnB's [CSS formatting](https://github.com/airbnb/css#formatting) is worthwhile, like in the JS section. What do you think?

**Comment by scottusrobus** [comment]
I have some thoughts with regards to this, related to Quartz. As I think we should include something about that, since a lot of our styling is Quartz-based classes. 

But would love to all chat in person first. Maybe we can find a time today or early this week.

**Comment by scottusrobus** [comment]
added quartz sass/css guidelines. 
ready to merge.

**Review by scottusrobus — APPROVED** [review]

**Pull request merged**
